# SITE CONFIGURATION
baseurl: "/DIGIfor1Health"
url: "https://sylhare.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Hemsida                                             # site's title
description: "Website for DIGIfor1Health project"      # used by search engines
  Förordningen om det europeiska hälsodataområdet European Health Data Space EHDS pekar ut en riktning för en paneuropeisk primär- och sekundäranvändning av hälsodata, till nytta för individen, vård och omsorg, akademi, näringsliv, och Sverige som kunskapsnation. Programmet för ett digitalt Europa (DIGITAL) är ett EU-finansieringsprogram som pågår under 2021–2027 med en totalbudget på 7,6 miljarder euro. Det syftar till att bygga digital kapacitet och infrastruktur inom EU med fokus på att underlätta bred användning av digital teknik och sätta resultat från forskning på marknaden. Fyra EU-DIGITAL-projekt med fokus på hälsodata har fått finansiering för perioden 2022–2027 med svenskt deltagande: 1) Genomic Data Infrastructure GDI (EHDS Genomics), 2) The European Federation for Cancer Images EUCAIM (EHDS Cancer Imaging), 3) European Digital Innovation Hub Health Data Sweden (HDS) och 4) Testing and Experimentation Facility for Health AI and Robotics (TEF-Health). I samband med detta har SciLifeLab, under januari – augusti 2023, lett den Vinnova-stödda förstudien (Dnr 2022-03542) för att skapa synergier mellan dessa DIGITAL-projekten. Förstudien visade på ett stort behov av nationellt samarbete mellan dessa fyra projekt under de kommande åren där även Genomic Medicine Sweden (GMS) som utvecklar Nationella Genomikplattformen (NGP) ska ingå. Detta för att på bästa sätt kunna göra hälsodata interoperabla för effektivt nyttjande, inklusive återkoppling till individen/patienten och hälso- och sjukvården, vilket är avgörande för att långsiktigt möjliggöra jämställd och hållbar hälsa. Syftet med DIGIfor1healthSE är effektivt nyttjande av den expertis som gemensamt finns inom ramen för dessa fyra EU-DIGITAL-projekten inom hälsodata i Sverige och det nationella initiativet Genomic Medicine Sweden (GMS), för att öka synergierna och tillsammans angripa de frågeställningar som behöver adresseras. 
avatar: assets/img/SciLifeLab.jpg                       # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Välkommen till DIGIfor1Health                  # Change Blog header text
header_feature_image: assets/img/header/doctor_R_h.jpeg
header_feature_image_responsive: true
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments options
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
